import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="BlueMagnet App Console", page_icon="📊", layout="wide")

st.markdown("""
<style>
.block-container {max-width:1500px;padding-top:1rem}
.metric {background:white;border:1px solid #dce4ef;border-radius:14px;padding:16px}
.small {color:#65748b;font-size:12px}
.value {font-size:27px;font-weight:750;color:#10233f}
h1,h2,h3 {color:#10233f}
</style>
""", unsafe_allow_html=True)

data = [
["Jul","LinkedIn","Paid Social",486,173,96,27,392000,94000,28.4],
["Jul","Google","Paid Search",410,151,82,22,318000,82000,26.8],
["Aug","Organic Search","Organic",375,139,74,19,276000,67000,25.7],
["Aug","Referral","Referral",220,91,51,15,214000,54000,29.4],
["Sep","Email","Email",190,73,38,11,156000,41000,28.9],
["Sep","LinkedIn","Paid Social",530,184,101,31,445000,108000,30.7],
["Oct","Google","Paid Search",470,165,88,24,361000,96000,27.3],
]
df=pd.DataFrame(data,columns=["Month","Source","Channel","MQL","SQL","Opportunity","Won","Pipeline","Revenue","WinRate"])

st.sidebar.title("BlueMagnet")
st.sidebar.caption("B2B Marketing Intelligence Console")
st.sidebar.markdown("### Navigation")
pages = [
    ("📊","Executive Dashboard"),
    ("🎯","B2B Performance"),
    ("🔗","Attribution"),
    ("🧭","Customer Journeys"),
    ("💼","Sales Pipeline"),
    ("🏢","Account Intelligence"),
    ("💰","ROI & Growth"),
]
if "page" not in st.session_state:
    st.session_state.page = "Executive Dashboard"
for icon, name in pages:
    if st.sidebar.button(f"{icon}  {name}", key=f"nav_{name}", use_container_width=True):
        st.session_state.page = name
        st.rerun()
page = st.session_state.page
model=st.sidebar.selectbox(
    "Attribution Model",
    ["Position-based","First touch","Last touch","Linear","Time decay"],
    key="attribution_model"
)
if st.sidebar.button("↻ Reset dashboard", use_container_width=True):
    for k in ["page","attribution_model"]:
        st.session_state.pop(k, None)
    st.rerun()
st.sidebar.markdown("---")
st.sidebar.success("Currency: ZAR (R)")
st.sidebar.caption("Prototype data • Connect CRM + analytics + advertising sources for production")

pipeline=df.Pipeline.sum()
revenue=df.Revenue.sum()
mql=df.MQL.sum()
sql=df.SQL.sum()
won=df.Won.sum()

def cards(items):
    cols=st.columns(len(items))
    for c,(label,value,delta) in zip(cols,items):
        c.markdown(f'<div class="metric"><div class="small">{label}</div><div class="value">{value}</div><div class="small">{delta}</div></div>',unsafe_allow_html=True)

st.title("BlueMagnet App Console")
st.caption("Unified B2B performance, attribution, pipeline and marketing intelligence")

cards([
("Pipeline Value",f"R{pipeline:,.0f}","+18.4%"),
("Won Revenue",f"R{revenue:,.0f}","+14.7%"),
("MQLs",f"{mql:,}","+21.3%"),
("SQLs",f"{sql:,}","+16.8%"),
("Win Rate",f"{won/df.Opportunity.sum():.1%}","+4.6 pp")
])

if page=="Executive Dashboard":
    st.header("Executive Overview")
    a,b=st.columns([1.5,1])
    with a:
        st.subheader("Pipeline & revenue by month")
        st.bar_chart(df.groupby("Month")[["Pipeline","Revenue"]].sum())
    with b:
        st.subheader("B2B funnel")
        funnel=pd.DataFrame({"Stage":["MQL","SQL","Opportunity","Won"],"Count":[mql,sql,df.Opportunity.sum(),won]})
        st.dataframe(funnel,use_container_width=True,hide_index=True)
    st.subheader("Channel performance")
    ch=df.groupby("Channel").agg(Pipeline=("Pipeline","sum"),Revenue=("Revenue","sum"),MQL=("MQL","sum")).sort_values("Pipeline",ascending=False)
    st.dataframe(ch.style.format({"Pipeline":"R{:,.0f}","Revenue":"R{:,.0f}"}),use_container_width=True)

elif page=="B2B Performance":
    st.header("B2B Performance")
    f1, f2 = st.columns(2)
    with f1:
        selected_channels = st.multiselect("Channel filter", sorted(df.Channel.unique()), default=sorted(df.Channel.unique()), key="b2b_channels")
    with f2:
        selected_months = st.multiselect("Period filter", sorted(df.Month.unique()), default=sorted(df.Month.unique()), key="b2b_months")
    filtered = df[df.Channel.isin(selected_channels) & df.Month.isin(selected_months)]
    st.subheader("Demand generation")
    st.bar_chart(filtered.groupby("Source")["MQL"].sum())
    st.subheader("Pipeline generated by channel")
    st.bar_chart(filtered.groupby("Channel")["Pipeline"].sum())
    st.dataframe(
    filtered[["Month","Source","Channel","MQL","SQL","Opportunity","Won","Pipeline","Revenue","WinRate"]]
    .style.format({"Pipeline":"R{:,.0f}","Revenue":"R{:,.0f}","WinRate":"{:.1f}%"}),
    use_container_width=True, hide_index=True
)

elif page=="Attribution":
    st.header(f"{model} Attribution")
    weights={"First touch":[1,0,0],"Last touch":[0,0,1],"Linear":[1/3,1/3,1/3],"Time decay":[.2,.3,.5],"Position-based":[.4,.2,.4]}
    w=weights[model]
    channels=df.Channel.unique()
    attr=[]
    for i,c in enumerate(channels):
        rev=df[df.Channel==c].Revenue.sum()
        attr.append([c,rev*w[-1],rev])
    ad=pd.DataFrame(attr,columns=["Channel","Attributed Revenue","Revenue Base"]).sort_values("Attributed Revenue",ascending=False)
    st.bar_chart(ad.set_index("Channel")["Attributed Revenue"])
    st.dataframe(ad.style.format({"Attributed Revenue":"R{:,.0f}","Revenue Base":"R{:,.0f}"}),use_container_width=True,hide_index=True)
    st.info("Compare models to understand how channel credit changes under different customer-journey assumptions.")

elif page=="Customer Journeys":
    st.header("Customer Journey Intelligence")
    paths=[
    ("Enterprise account","LinkedIn → Content → Webinar → Demo → Won","R86,000"),
    ("Technology account","Google → Landing Page → Email → Demo → Won","R72,000"),
    ("Finance account","Organic Search → Case Study → Email → Demo","R64,000"),
    ("Logistics account","Referral → Landing Page → Demo → Won","R58,000"),
    ]
    journey_df = pd.DataFrame(paths,columns=["Journey Type","Touchpoint Path","Attributed Revenue"])
    st.dataframe(journey_df,use_container_width=True,hide_index=True)
    selected_journey = st.selectbox("Click to inspect a journey", journey_df["Journey Type"], key="journey_select")
    detail = journey_df[journey_df["Journey Type"] == selected_journey].iloc[0]
    st.success(f"Selected: {detail['Journey Type']}  |  Path: {detail['Touchpoint Path']}  |  Attributed revenue: {detail['Attributed Revenue']}")
    st.info("Use these paths to identify high-value assisted conversions and optimize campaigns, landing pages and sales follow-up.")

elif page=="Sales Pipeline":
    st.header("Sales Pipeline")
    a,b,c=st.columns(3)
    a.metric("Open Pipeline","R1.84M")
    b.metric("Average Deal","R14.5K")
    c.metric("Sales Cycle","29 days")
    st.subheader("Pipeline by source")
    st.bar_chart(df.groupby("Source")["Pipeline"].sum())
    st.subheader("Pipeline table")
    st.dataframe(df[["Source","Channel","Opportunity","Pipeline","Won","Revenue"]].style.format({"Pipeline":"R{:,.0f}","Revenue":"R{:,.0f}"}),use_container_width=True,hide_index=True)

elif page=="Account Intelligence":
    st.header("Account Intelligence")
    accounts=pd.DataFrame([
    ["Apex Industrial","Technology","R342K","R96K","High"],
    ["Nova Health","Healthcare","R287K","R82K","High"],
    ["Kopano Energy","Energy","R264K","R74K","High"],
    ["Vertex Logistics","Logistics","R218K","R58K","Medium"],
    ["Northstar Finance","Financial Services","R196K","R52K","Medium"],
    ],columns=["Account","Industry","Pipeline","Won Revenue","Priority"])
    st.dataframe(accounts,use_container_width=True,hide_index=True)
    selected_account = st.selectbox("Click to inspect account", accounts["Account"], key="account_select")
    account = accounts[accounts["Account"] == selected_account].iloc[0]
    st.success(f"{account['Account']} • {account['Industry']} • Pipeline {account['Pipeline']} • Won revenue {account['Won Revenue']} • Priority {account['Priority']}")
    st.bar_chart(accounts.set_index("Account")["Won Revenue"].str.replace("R","").str.replace("K","").astype(float))

else:
    st.header("ROI & Growth")
    spend=198000
    st.metric("Marketing Spend",f"R{spend:,.0f}")
    st.metric("Attributed Revenue",f"R{revenue:,.0f}")
    st.metric("Revenue / Spend",f"{revenue/spend:.2f}x")
    st.subheader("ROI by channel")
    roi=df.groupby("Channel").Revenue.sum().to_frame()
    costs={"Paid Social":70000,"Paid Search":56000,"Organic":18000,"Referral":14000,"Email":9000}
    roi["Spend"]=roi.index.map(costs).fillna(0)
    roi["ROAS"]=roi.Revenue/roi.Spend
    st.bar_chart(roi["ROAS"])
    st.dataframe(roi.style.format({"Revenue":"R{:,.0f}","Spend":"R{:,.0f}","ROAS":"{:.2f}x"}),use_container_width=True)

st.markdown("---")
st.caption("BlueMagnet App Console • ZAR / South African Rand • Designed for CRM, web analytics, advertising and marketing automation integration")
